# Sample .travis.yml for R projects.
# Taken from my fork of Craig Citro's r-travis
#
# See https://github.com/eddelbuettel/r-travis/
# and https://github.com/craigcitro/r-travis
#
# See README.md for instructions.

language: c

sudo: required

dist: trusty

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=FALSE

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh install_aptget r-cran-rcpp r-cran-rcpparmadillo r-cran-inline r-cran-deoptim r-cran-lattice

script:
  - ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change

